text2image:
  name: 'test01'
  output_dir: './outputs'
  sd_model: 'beautifulRealistic_v60.safetensors [bc2f30f4ad]'
  prompt: 'girl'
  negative_prompt: 'nsfw'
  batch_count: 10
  batch_size: 1
  width: 400
  height: 640
  cfg_scale: 7
  sampler_name: "DPM++ 2M Karras"
  steps: 20
  enable_hr: True
  hr_scale: 2
  #hr_upscaler: "SwinIR 4x"
  hr_upscaler: "Latent"
  hr_second_pass_steps: 0
  denoising_strength: 0.7
