text2image:
  name: 'test02'
  output_dir: './outputs'
  sd_model: 'yayoiMix_v25.safetensors [ca28aa4a44]'
  prompt: '(realistic, photo-realistic:1.37), (masterpiece), (best quality:1.4), (ultra high res:1.2), (RAW photo:1.2), (sharp focus:1.3), (full body:1.2), elegant, 1girl, 16k, highly detail face, (shine hair:1.3), BREAK,
(huge breasts:1.3), (bustier,garter straps:1.2), scenery, shiny skin, Japanese idle, glamorous, beautiful detailed eyes, looking at viewer, cute, makeup'
  negative_prompt: 'EasyNegativeV2, (text:2), (worst quality:2),(low quality:2),(normal quality:2),(deformed:1.3),(monochrome:1.2),(grayscale:1.2), ugly face, (missing fingers), extra fingers, (six fingers:1.2), (bad anatomy:1.2), skin spots acnes, skin blemishes, age spot, cartoon, nipple'
  batch_count: 100
  batch_size: 1
  width: 400
  height: 640
  cfg_scale: 7
  sampler_name: "DPM++ 2M Karras"
  steps: 20
  enable_hr: True
  hr_scale: 2
  #hr_upscaler: "SwinIR 4x"
  hr_upscaler: "Latent"
  hr_second_pass_steps: 0
  denoising_strength: 0.7



